<a href="https://colab.research.google.com/github/owilli38/DSBA-6162/blob/main/DSBA6162_Word_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 53.8 MB/s eta 0:00:00


In [ ]:
# Import packages
import numpy as np
import warnings
warnings.filterwarnings(action="ignore")#ignore all warning messages in this script
from gensim.models import Word2Vec
from nltk.tokenize import sent_tokenize, word_tokenize
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


**Problem 1**

In [ ]:
import gensim.downloader
list(gensim.downloader.info()["models"].keys())

['fasttext-wiki-news-subwords-300',
 'conceptnet-numberbatch-17-06-300',
 'word2vec-ruscorpora-300',
 'word2vec-google-news-300',
 'glove-wiki-gigaword-50',
 'glove-wiki-gigaword-100',
 'glove-wiki-gigaword-200',
 'glove-wiki-gigaword-300',
 'glove-twitter-25',
 'glove-twitter-50',
 'glove-twitter-100',
 'glove-twitter-200',
 '__testing_word2vec-matrix-synopsis']

In [ ]:
pretrained_glove_model = gensim.downloader.load("glove-wiki-gigaword-50")

[==================================================] 100.0% 66.0/66.0MB downloaded


In [ ]:
seven_words = ["I", "love", "deep", "learning", "and", "text", "mining"]
word_embeddings_dict = {}

for word in seven_words:
  try:
    word_embeddings_dict[word] = pretrained_glove_model[word]
  except KeyError:
    print(f"Word '{word}' not found in the vocabulary.")

print("\nDictionary of word embeddings:")
print(word_embeddings_dict)

Word 'I' not found in the vocabulary.

Dictionary of word embeddings:
{'love': array([-0.13886  ,  1.1401   , -0.85212  , -0.29212  ,  0.75534  ,
        0.82762  , -0.3181   ,  0.0072204, -0.34762  ,  1.0731   ,
       -0.24665  ,  0.97765  , -0.55835  , -0.090318 ,  0.83182  ,
       -0.33317  ,  0.22648  ,  0.30913  ,  0.026929 , -0.086739 ,
       -0.14703  ,  1.3543   ,  0.53695  ,  0.43735  ,  1.2749   ,
       -1.4382   , -1.2815   , -0.15196  ,  1.0506   , -0.93644  ,
        2.7561   ,  0.58967  , -0.29473  ,  0.27574  , -0.32928  ,
       -0.201    , -0.28547  , -0.45987  , -0.14603  , -0.69372  ,
        0.070761 , -0.19326  , -0.1855   , -0.16095  ,  0.24268  ,
        0.20784  ,  0.030924 , -1.3711   , -0.28606  ,  0.2898   ],
      dtype=float32), 'deep': array([ 0.31445 ,  1.2024  ,  0.066651, -0.20096 , -0.049636,  0.66882 ,
       -0.049386,  0.44174 ,  0.1799  , -0.10196 , -0.43674 ,  0.12076 ,
       -0.12495 ,  0.43378 , -0.87784 ,  0.010281,  0.54592 , -0.28928 ,
 

In [ ]:
# Find the word embedding for "deep"
deep_embedding = pretrained_glove_model["deep"]
print("Embedding for 'deep':")
print(deep_embedding)

# Find the word embedding for "text"
text_embedding = pretrained_glove_model["text"]
print("\nEmbedding for 'text':")
print(text_embedding)

Embedding for 'deep':
[ 0.31445   1.2024    0.066651 -0.20096  -0.049636  0.66882  -0.049386
  0.44174   0.1799   -0.10196  -0.43674   0.12076  -0.12495   0.43378
 -0.87784   0.010281  0.54592  -0.28928  -0.46115  -0.32058  -0.69094
  0.49733   0.40657  -0.90062   0.69699  -1.1536   -0.12229   1.0657
  0.93207   0.20439   3.3004    0.14223   0.46493   0.075359 -0.56755
  0.30769  -1.1251   -0.37871   0.57479  -0.12629   0.13589   0.10633
  0.058432  0.40321   0.10243   0.12004   0.41383   0.051987 -0.5835
 -1.1159  ]

Embedding for 'text':
[ 0.32615    0.36686   -0.0074905 -0.37553    0.66715    0.21646
 -0.19801   -1.1001    -0.42221    0.10574   -0.31292    0.50953
  0.55775    0.12019    0.31441   -0.25043   -1.0637    -1.3213
  0.87798   -0.24627    0.27379   -0.51092    0.49324    0.52243
  1.1636    -0.75323   -0.48053   -0.11259   -0.54595   -0.83921
  2.9825    -1.1916    -0.51958   -0.39365   -0.1419    -0.026977
  0.66296    0.16574   -1.1681     0.14443    1.6305    -0.17216

**Problem 2**

In [ ]:
with open("/content/drive/MyDrive/ColabData/novels_by_hgwells.zip", "r") as file:
  src = file.read()
  f = src.replace("\n", " ")  # Replace the new line character with space

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
import zipfile
zip_file_path = "/content/drive/MyDrive/ColabData/novels_by_hgwells.zip"

In [ ]:
novel_contents = {}
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    file_list = zip_ref.namelist()
    for file_name in file_list:
        if file_name.endswith('.txt'):
            with zip_ref.open(file_name, 'r') as file:
                novel_contents[file_name] = file.read().decode('utf-8')

print(f"Loaded contents of {len(novel_contents)} novels.")

Loaded contents of 5 novels.


In [ ]:
# Print the first 500 characters of one of the novels to inspect the markers
print(list(novel_contents.values())[0][:500])

The Project Gutenberg eBook of The Time Machine
    
This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg License included with this ebook or online
at www.gutenberg.org. If you are not located in the United States,
you will have to check the laws of the country where you are located
before using this eB


In [ ]:
cleaned_novel_contents = {}
start_marker = "*** START OF THE PROJECT GUTENBERG EBOOK"
end_marker = "*** END OF THE PROJECT GUTENBERG EBOOK"

for novel_name, content in novel_contents.items():
    start_index = content.find(start_marker)
    end_index = content.find(end_marker)

    if start_index != -1 and end_index != -1:
        cleaned_content = content[start_index + len(start_marker):end_index].strip()
        cleaned_novel_contents[novel_name] = cleaned_content
    else:
        print(f"Markers not found in {novel_name}. Skipping cleaning.")

print(f"Cleaned content for {len(cleaned_novel_contents)} novels.")

Cleaned content for 5 novels.


In [ ]:
combined_text = ""
for content in cleaned_novel_contents.values():
  combined_text += content + " "

print(f"Combined text length: {len(combined_text)}")

Combined text length: 1928326


In [ ]:
from nltk.tokenize import sent_tokenize
sentences = sent_tokenize(combined_text)
print(f"Number of sentences: {len(sentences)}")
print("First 5 sentences:")
for i, sentence in enumerate(sentences[:5]):
    print(f"{i+1}: {sentence}")

Number of sentences: 20162
First 5 sentences:
1: THE TIME MACHINE ***




The Time Machine

An Invention

by H. G. Wells


CONTENTS

 I Introduction
 II The Machine
 III The Time Traveller Returns
 IV Time Travelling
 V In the Golden Age
 VI The Sunset of Mankind
 VII A Sudden Shock
 VIII Explanation
 IX The Morlocks
 X When Night Came
 XI The Palace of Green Porcelain
 XII In the Darkness
 XIII The Trap of the White Sphinx
 XIV The Further Vision
 XV The Time Traveller’s Return
 XVI After the Story
 Epilogue




 I.
2: Introduction


The Time Traveller (for so it will be convenient to speak of him) was
expounding a recondite matter to us.
3: His pale grey eyes shone and
twinkled, and his usually pale face was flushed and animated.
4: The fire
burnt brightly, and the soft radiance of the incandescent lights in the
lilies of silver caught the bubbles that flashed and passed in our
glasses.
5: Our chairs, being his patents, embraced and caressed us rather
than submitted to be sat upon, a

In [ ]:
tokenized_words = []
for sentence in sentences:
  tokenized_words.append(word_tokenize(sentence.lower()))

print(tokenized_words[0])

['the', 'time', 'machine', '*', '*', '*', 'the', 'time', 'machine', 'an', 'invention', 'by', 'h.', 'g.', 'wells', 'contents', 'i', 'introduction', 'ii', 'the', 'machine', 'iii', 'the', 'time', 'traveller', 'returns', 'iv', 'time', 'travelling', 'v', 'in', 'the', 'golden', 'age', 'vi', 'the', 'sunset', 'of', 'mankind', 'vii', 'a', 'sudden', 'shock', 'viii', 'explanation', 'ix', 'the', 'morlocks', 'x', 'when', 'night', 'came', 'xi', 'the', 'palace', 'of', 'green', 'porcelain', 'xii', 'in', 'the', 'darkness', 'xiii', 'the', 'trap', 'of', 'the', 'white', 'sphinx', 'xiv', 'the', 'further', 'vision', 'xv', 'the', 'time', 'traveller', '’', 's', 'return', 'xvi', 'after', 'the', 'story', 'epilogue', 'i', '.']


In [ ]:
import re

cleaned_tokenized_words = []
for sentence in tokenized_words:
    cleaned_sentence = [re.sub(r'[^a-z]', '', word) for word in sentence]
    cleaned_sentence = [word for word in cleaned_sentence if word]
    if cleaned_sentence:
        cleaned_tokenized_words.append(cleaned_sentence)

print("First 5 cleaned and tokenized sentences:")
for i, sentence in enumerate(cleaned_tokenized_words[:5]):
    print(f"{i+1}: {sentence}")

First 5 cleaned and tokenized sentences:
1: ['the', 'time', 'machine', 'the', 'time', 'machine', 'an', 'invention', 'by', 'h', 'g', 'wells', 'contents', 'i', 'introduction', 'ii', 'the', 'machine', 'iii', 'the', 'time', 'traveller', 'returns', 'iv', 'time', 'travelling', 'v', 'in', 'the', 'golden', 'age', 'vi', 'the', 'sunset', 'of', 'mankind', 'vii', 'a', 'sudden', 'shock', 'viii', 'explanation', 'ix', 'the', 'morlocks', 'x', 'when', 'night', 'came', 'xi', 'the', 'palace', 'of', 'green', 'porcelain', 'xii', 'in', 'the', 'darkness', 'xiii', 'the', 'trap', 'of', 'the', 'white', 'sphinx', 'xiv', 'the', 'further', 'vision', 'xv', 'the', 'time', 'traveller', 's', 'return', 'xvi', 'after', 'the', 'story', 'epilogue', 'i']
2: ['introduction', 'the', 'time', 'traveller', 'for', 'so', 'it', 'will', 'be', 'convenient', 'to', 'speak', 'of', 'him', 'was', 'expounding', 'a', 'recondite', 'matter', 'to', 'us']
3: ['his', 'pale', 'grey', 'eyes', 'shone', 'and', 'twinkled', 'and', 'his', 'usually', '

In [ ]:
# Train CBOW model, min_count= 1 the minumum frequency of a word to be considered, basically = 1 means all words are considered
cbow_model = Word2Vec(sentences=cleaned_tokenized_words, min_count=1, vector_size=100, window=5, workers=1, seed=2024)

In [ ]:
# Accessing word vectors
soldiers_embedding = cbow_model.wv["soldiers"]
soldiers_embedding

array([-0.16178519,  0.05469715, -0.01928971,  0.0328531 , -0.22459379,
       -0.0706311 ,  0.02255885,  0.12726709,  0.11228341,  0.23449261,
        0.1657856 , -0.0056017 , -0.03916209, -0.02838366, -0.27611437,
        0.07465969, -0.08116902, -0.12110235,  0.02083913,  0.20180307,
        0.04779929, -0.18391238,  0.14515735, -0.0799435 , -0.08384396,
       -0.10332527, -0.18094124, -0.03637947, -0.25439954, -0.05006322,
       -0.10119782, -0.02051347,  0.2453411 , -0.10316004,  0.07523695,
        0.08417674, -0.2210605 , -0.09092371, -0.27052045, -0.05366279,
        0.06800242,  0.07482928,  0.052819  , -0.04213725,  0.27403298,
       -0.14395301, -0.11419918, -0.2096227 , -0.11592767,  0.2918546 ,
        0.19008821, -0.03207022,  0.03400819,  0.19807489, -0.03446738,
       -0.01334772, -0.07218786, -0.00936576,  0.03069368, -0.09920096,
        0.06120434, -0.02218848,  0.0724734 , -0.01242984, -0.30887455,
        0.14521377,  0.06082198,  0.10527773,  0.04207381,  0.09

In [ ]:
road_embedding = cbow_model.wv["road"]
road_embedding

array([-0.8048422 , -0.22151385, -0.29268104,  0.11661944, -0.8069631 ,
       -0.61083883,  0.38200718,  0.03895012,  0.37928396,  0.9270499 ,
        0.06881159, -0.1049026 ,  0.12013513, -0.15974993, -1.0134203 ,
        0.00706525, -0.21737677, -0.17365913,  0.13335393,  0.85245717,
        0.02616179, -0.5498717 ,  0.6195085 , -0.56438565, -0.47654885,
       -0.47964287, -0.63555723,  0.02446435, -1.0708505 , -0.39189854,
       -0.12022678,  0.03234294,  0.52935743, -0.10870365,  0.5737262 ,
        0.55267185, -0.6079162 , -0.19415991, -1.2290833 , -0.4559802 ,
        0.246574  ,  0.23836598,  0.37951532,  0.09854048,  1.0727681 ,
       -0.6294799 , -0.3672469 , -0.5619839 , -0.20663811,  0.74931175,
        0.58008814,  0.03619054,  0.3248374 ,  0.7090352 , -0.07818832,
       -0.08570602, -0.34578443, -0.28249052, -0.30888987, -0.27520743,
        0.02722822, -0.18474957,  0.35193494, -0.11949973, -0.9611936 ,
        0.03238992,  0.31066918,  0.16562529,  0.02957443,  0.45

In [ ]:
# Finding most similar words
similar_words = cbow_model.wv.most_similar("road", topn=10)
similar_words

[('window', 0.9964198470115662),
 ('darkness', 0.9946605563163757),
 ('corner', 0.9941814541816711),
 ('passage', 0.9928684830665588),
 ('fence', 0.9927415251731873),
 ('shadow', 0.9927010536193848),
 ('sea', 0.9926543235778809),
 ('edge', 0.9912459850311279),
 ('chair', 0.9910342693328857),
 ('tops', 0.9909993410110474)]

In [ ]:
# Train Skip Gram model. sg=1 means it is a skip-gram model. If sg=0, it would be a CBOW model.
skip_gram_model = Word2Vec(sentences=cleaned_tokenized_words, min_count=1, vector_size=100, window=5, workers=1, seed=2024, sg=1)

In [ ]:
# Accessing word vectors
soldier_embedding = skip_gram_model.wv["soldier"]
soldier_embedding

array([-0.04530066,  0.09393256,  0.00560581,  0.03300663, -0.19665724,
        0.03789129, -0.0560987 ,  0.15727226,  0.02741368,  0.23102896,
        0.30535233, -0.03941691, -0.16593166, -0.03851601, -0.18986244,
        0.1990439 , -0.16734485, -0.06435407,  0.12213738,  0.23833527,
        0.06226468, -0.20127812,  0.07718593, -0.07893607, -0.0591576 ,
       -0.10779952, -0.09836062, -0.07802978, -0.22878276,  0.0651363 ,
       -0.1082561 , -0.02444301,  0.23847821, -0.12705669,  0.056999  ,
        0.02820683, -0.25249746, -0.14130381, -0.2617403 , -0.05171452,
        0.01050688,  0.12086827,  0.08267979, -0.13147281,  0.12940075,
       -0.08516779, -0.08547816, -0.24207841, -0.24404274,  0.3940482 ,
        0.21167968, -0.09845351,  0.01665072,  0.16804336, -0.0945928 ,
        0.0340865 , -0.05281272, -0.0451587 ,  0.02978575, -0.08821186,
        0.04466206,  0.10643891,  0.01600278,  0.03370802, -0.3313413 ,
        0.21871427, -0.03355186,  0.19975601,  0.08759224,  0.04

In [ ]:
# Accessing word vectors
road_embedding = skip_gram_model.wv["road"]
road_embedding

array([-0.37494496, -0.10525256, -0.04566465,  0.11320145, -0.28942358,
       -0.23461069,  0.05096478, -0.15094864, -0.0323011 ,  0.56798196,
        0.14253931,  0.11200424, -0.03710081, -0.247821  , -0.5472047 ,
       -0.03120772, -0.27977723, -0.13021824,  0.12006868,  0.34603247,
        0.21434858, -0.35000607,  0.41060588, -0.38646844, -0.02781211,
       -0.4259983 , -0.12879157,  0.10211205, -0.6555139 , -0.13988154,
        0.17451698, -0.13673769,  0.39145854, -0.01367603,  0.40492842,
        0.2838623 , -0.5025894 , -0.25165242, -0.5849699 , -0.1449533 ,
        0.12900944, -0.04574975,  0.4616106 , -0.04752597,  0.3058429 ,
       -0.29757082, -0.16302195, -0.31386212,  0.06277255,  0.3796186 ,
        0.5085921 ,  0.17188397,  0.13358122,  0.43828207, -0.05344812,
       -0.15580447, -0.30028588, -0.12217076, -0.01586013, -0.22788863,
        0.08692126, -0.01917251,  0.13465188, -0.12342874, -0.43263727,
        0.06306347, -0.17229673,  0.22035004,  0.02800278,  0.11

In [ ]:
# Finding most similar words
similar_words = skip_gram_model.wv.most_similar("road", topn=10)
similar_words

[('river', 0.964411735534668),
 ('railway', 0.962736189365387),
 ('mountain', 0.9499139785766602),
 ('maybury', 0.947864294052124),
 ('lane', 0.9474352598190308),
 ('opposite', 0.9439123272895813),
 ('main', 0.9438663125038147),
 ('path', 0.9433651566505432),
 ('west', 0.9428965449333191),
 ('meadows', 0.9419018030166626)]